### ISSUE TITLE
Error using connect-deps with ky (a package for fetch abstraction)

### ISSUE THREAD

**Issue by pcowgill** [hugomrdias/connect-deps#20]
```
➜  js-ipfs-http-client git:(feature/logging) ✗ connect-deps link ../ky --connect --watch
✔ Linking ../ky
✖ Packing ky
Error: ENOENT: no such file or directory, rename '[parent-dir]/js-ipfs-http-client/.connect-deps-cache/
> ky@0.15.0 prepare [parent-dir]/ky
> npm run build


> ky@0.15.0 build [parent-dir]/ky
> rollup index.js --format=umd --name=ky --file=umd.js

ky-0.15.0.tgz' -> '[parent-dir]/js-ipfs-http-client/.connect-deps-cache/ky-0.15.0-1580141804371.tgz'
    at Object.renameSync (fs.js:598:3)
    at Object.pack (~/.nvm/versions/node/v10.16.3/lib/node_modules/connect-deps/cli.js:96:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by hugomrdias** [comment]
can't repro locally this issue

**Comment by pcowgill** [comment]
@hugomrdias Can or cannot?

**Comment by pcowgill** [comment]
Steps to reproduce on macOS 10.15.3 in a zsh terminal using node via `nvm`:
```
➜  experiments mkdir connect-deps-repro
➜  experiments cd connect-deps-repro 
➜  connect-deps-repro npm i -g connect-deps
/Users/paulcowgill/.nvm/versions/node/v12.14.1/bin/connect-deps -> /Users/paulcowgill/.nvm/versions/node/v12.14.1/lib/node_modules/connect-deps/cli.js
+ connect-deps@0.2.0
updated 1 package in 6.884s
➜  connect-deps-repro connect-deps --version
0.2.0
➜  connect-deps-repro npm --version
6.13.4
➜  connect-deps-repro node --version
v12.14.1
➜  connect-deps-repro ls
➜  connect-deps-repro git clone https://github.com/sindresorhus/ky.git
➜  connect-deps-repro cd ky
➜  ky git:(master) git checkout 6e929dbe1630b491889c463b4ee563cf15abfad9
Note: checking out '6e929dbe1630b491889c463b4ee563cf15abfad9'.
HEAD is now at 6e929db 0.15.0
➜  ky git:(6e929db) cd ..        
➜  connect-deps-repro git clone https://github.com/ipfs/js-ipfs-http-client.git
➜  connect-deps-repro ls
js-ipfs-http-client ky
➜  connect-deps-repro cd js-ipfs-http-client 
➜  js-ipfs-http-client git:(master) connect-deps link ../ky                  
✔ Linking ../ky
➜  js-ipfs-http-client git:(master) ✗ connect-deps connect   
✖ Packing ky
Error: Command failed with exit code 1 (EPERM): npm pack /Users/paulcowgill/Code/general/experiments/connect-deps-repro/ky
    at makeError (/Users/paulcowgill/.nvm/versions/node/v12.14.1/lib/node_modules/connect-deps/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/paulcowgill/.nvm/versions/node/v12.14.1/lib/node_modules/connect-deps/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.pack (/Users/paulcowgill/.nvm/versions/node/v12.14.1/lib/node_modules/connect-deps/cli.js:94:25)
    at async packInstall (/Users/paulcowgill/.nvm/versions/node/v12.14.1/lib/node_modules/connect-deps/cli.js:313:13)
    at async connect (/Users/paulcowgill/.nvm/versions/node/v12.14.1/lib/node_modules/connect-deps/cli.js:207:5)
```

**Comment by pcowgill** [comment]
`.connect-deps-cache` dir is empty
`.connect-deps.json` contents:
```
{
	"ky": {
		"name": "ky",
		"path": "/Users/paulcowgill/Code/general/experiments/connect-deps-repro/ky",
		"version": "0.15.0",
		"watch": "**/*",
		"snapshot": {
			"version": "^0.15.0",
			"type": "normal"
		}
	}
}
```

**Comment by pcowgill** [comment]
@hugomrdias Can you please share your minimal repro of it working? Thanks!

**Comment by pcowgill** [comment]
@hugomrdias Thanks for finding a fix for this!
